### ISSUE TITLE
Color genotype tracks

### ISSUE THREAD

**Issue by mattmaurano** [mauranolab/mapping#215]
Can you see whether we can override the per-sample coloring for the genotype tracks so that we can give hzref/het/hznonref distinct colors?

Probably the .bb files would need to be regenerated as well.

**Comment by mattmaurano** [comment]
bumping this -- John, can you look in to this?

**Comment by cadley-nyulangone** [comment]
Will do.

**Comment by cadley-nyulangone** [comment]
The "genotypes.bb" files are built in a for loop in callsnpsMerge.sh (lines
181 - 201).

To get them to print in color, we need to add four columns to the
genotypes.ucsc.bed file, which is produced just prior to the call to
bedToBigBed in the loop.

The existing genotypes.ucsc.bed files are bed5 files, and have this form:
   Sox2_Sox2_46kb_dDistalLCR_marker    1709    1710
 Sox2_Sox2_46kb_dDistalLCR_marker:1710_A      127
   Sox2_Sox2_46kb_dDistalLCR_marker    4535    4536
 Sox2_Sox2_46kb_dDistalLCR_marker:4536_T      127
   Sox2_Sox2_46kb_dDistalLCR_marker    21600   21601
Sox2_Sox2_46kb_dDistalLCR_marker:21601_CCG   127


We need to append these 4 columns to each row:

  *  strand    thickStart     thickEnd     colorCode*

   - strand is "+" or "-".  For this application, I think we can just use
   "+" everywhere.
   - thickStart and thickEnd can be equal, and can also be the same as the
   start position value. It affects the thickness of the colored line.
   - colorCode is formatted like this:   255,0,0  or 0,255,0  etc.


A problem is to figure out what color code to use for each line of the
genotypes.ucsc.bed file.

I think that can be solved by looking inside the genotypes.starch file,
which is produced prior to the genotypes.bb file within the loop.

The genotypes.starch file has this format:
Sox2_Sox2_46kb_dDistalLCR_marker        1709    1710
 Sox2_Sox2_46kb_dDistalLCR_marker:1710_A         127     G       A       A
      255,0   19      0       19
Sox2_Sox2_46kb_dDistalLCR_marker        4535    4536
 Sox2_Sox2_46kb_dDistalLCR_marker:4536_T         127     A       T       T
      219,0   991     86      905
Sox2_Sox2_46kb_dDistalLCR_marker        21600   21601
Sox2_Sox2_46kb_dDistalLCR_marker:21601_CCG      127     C       CCG     CCG
    237,0   20      2       18

The last two columns are the number of ref and alt allele reads.  I think
if the number pattern means:



*#  , 0  ===> ref#1 , #2 ===> het0  , #  ===> alt*


Is that right ?

Knowing the ref/het/alt identity of each of the genotypes.starch lines will
then let us append the desired color codes to the genotypes.ucsc.bed file
lines.

bedToBigBed would then run as usual, except we need to add an "as" file as
another resource for it.  The "as" file defines the fields, and is needed
when one of the fields is a color field. It does not depend on the track.
One small common file can be used for all the tracks.

We'll also need to add a "itemRgb" line to the Daler python output to get
it to pay attention to the color field.

What do you think of this?

John

**Comment by mattmaurano** [comment]
Good. A few points:

So you can override the group coloring with itemRGB just for the genotype tracks, so the coverage, etc. tracks keep the group colors?

You'll need to double check in parseSamtoolsGenotypesToBedFiles.pl that the alleles are output as ref/nonref

What happens in haploid genomes with 1 allele, like cegsvectors?

Can you manually mock up using custom tracks and show a screenshot of all the track types for a single sample? Try BS08118A over the distal sox2 LCR, and get the blue/yellow colors that Raquel O has been using for her genotype tracks.

**Comment by cadley-nyulangone** [comment]
I checked parseSamtoolsGenotypesToBedFiles.pl, and it prints ref then alt:

*83             print $outFH
"$bed3\t$id\t$GQ\t$ref\t$alt\t$betterGT\t$PL\t$DP\t$numRef\t$numNonRef\n";*


I still need to check the haploid scenario.

I've attached a pdf of BS08118A.  It shows the usual coverage, variants,
and genotypes tracks, then one more custom genotype track where they are
colored blue / yellow / grey  for het / hz_nonref / hz_ref.
 The color shades are what  Raquel uses.  There are no greys in this
particular example.

I'm uncertain as to the right method for identifying het vs hz alleles. I
found a paper which said one old way was to check if the percent of alt
reads was between 20% and 80% of the total. If so, then call it het.  If
not, then hz.  I used that method in my example.  Is there a better way?

Here is the genotypes.bed file:

Sox2_Sox2_46kbp_dDistalLCR  1851    1852
 Sox2_Sox2_46kbp_dDistalLCR:1852_A   127 G   A   A   164,0   468 52  416
Sox2_Sox2_46kbp_dDistalLCR  1916    1917
 Sox2_Sox2_46kbp_dDistalLCR:1917_T   127 A   T   T   255,0   1269    16
 1253
Sox2_Sox2_46kbp_dDistalLCR  2149    2150
 Sox2_Sox2_46kbp_dDistalLCR:2150_G   122 A   G   G   181,64  92  16  76
Sox2_Sox2_46kbp_dDistalLCR  2499    2500
 Sox2_Sox2_46kbp_dDistalLCR:2500_T   101 C   T   T   255,157 30  10  20
Sox2_Sox2_46kbp_dDistalLCR  15908   15910
Sox2_Sox2_46kbp_dDistalLCR:15909_T  107 TC  T   T   162,59  18  5   13
Sox2_Sox2_46kbp_dDistalLCR  22227   22228
Sox2_Sox2_46kbp_dDistalLCR:22228_A  127 G   A   A   208,36  12  2   10
Sox2_Sox2_46kbp_dDistalLCR  24008   24009
Sox2_Sox2_46kbp_dDistalLCR:24009_C  119 T   C   C   215,99  18  6   12
Sox2_Sox2_46kbp_dDistalLCR  24022   24023
Sox2_Sox2_46kbp_dDistalLCR:24023_C  127 T   C   C   218,36  15  3   12
Sox2_Sox2_46kbp_dDistalLCR  26403   26404
Sox2_Sox2_46kbp_dDistalLCR:26404_G  104 C   G   G   211,110 16  5   11
Sox2_Sox2_46kbp_dDistalLCR  30483   30484
Sox2_Sox2_46kbp_dDistalLCR:30484_G  127 A   G   G   254,106 22  6   16
Sox2_Sox2_46kbp_dDistalLCR  33286   33287
Sox2_Sox2_46kbp_dDistalLCR:33287_C  119 G   C   C   196,81  15  4   11
Sox2_Sox2_46kbp_dDistalLCR  34610   34611
Sox2_Sox2_46kbp_dDistalLCR:34611_G  107 A   G   G   219,115 17  6   11
Sox2_Sox2_46kbp_dDistalLCR  42560   42561
Sox2_Sox2_46kbp_dDistalLCR:42561_G  108 A   G   G   232,127 19  6   13
Sox2_Sox2_46kbp_dDistalLCR  44008   44009
Sox2_Sox2_46kbp_dDistalLCR:44009_A  127 G   A   A   215,87  14  4   10
Sox2_Sox2_46kbp_dDistalLCR  44538   44539
Sox2_Sox2_46kbp_dDistalLCR:44539_G  103 A   G   G   185,85  14  4   10
Sox2_Sox2_46kbp_dDistalLCR  45097   45098
Sox2_Sox2_46kbp_dDistalLCR:45098_C  127 G   C   C   255,0   282 13  269
Sox2_Sox2_46kbp_dDistalLCR  45104   45105
Sox2_Sox2_46kbp_dDistalLCR:45105_A  127 G   A   A   151,0   252 23  229


John

**Comment by mattmaurano** [comment]
I don't see the attachment.

To identify het vs hz, compare the betterGT column to the ref/alt alleles

**Comment by cadley-nyulangone** [comment]
Has attachment

**Comment by cadley-nyulangone** [comment]
I don't understand what the het scenario will look like when comparing
betterGT column to the ref/alt columns.  Will  betterGT have two letters,
like "AT" ?

**Comment by mattmaurano** [comment]
Take a look at an example gt file, but yes there should be something like "A/T" vs "A/A".

**Comment by cadley-nyulangone** [comment]
OK, I am now using the betterGT field.

For the haploid case, the color output is always for homozygous, either
yellow or grey.  Yellow is for non_ref. Grey is for ref.

For the diploid case, we could get the same  homozygous yellow / grey as
above. But we could also get the blue heterozygous output.

Some examples are attached. The current coverage/variants/genotypes tracks
appear first, followed by the new custom colored genotypes.

John

**Comment by mattmaurano** [comment]
OK, this is looking good and I think you have scoped out the main design issues. Go ahead and make a PR.

One question: what happens if MakeTrackhub.py sets itemRgb for genotype tracks not including any color info? Ideally it would fail gracefully (either no color, or using the main group color). If it gives an error we will need to migrate and regenerate all the .bb files.

**Comment by cadley-nyulangone** [comment]
I added "itemRbg on"  to the dev hub, and refreshed it.  The tracks display
with the same colors as they always did.

I had left in the *color=curSample['Color']* line in python's genotypes
track definition, so I suppose that is why it works.

When I take out the  *color=curSample['Color']*  line, then the
genotype track is still displayed OK, but in black.

I'm not sure if the "itemRbg on" will take priority over
*color=curSample['Color']*  when there is a suitable bb file, or if I will
need to delete it to allow itemRgb to work.  I'll leave it in for now to
see what happens.

John

**Comment by mattmaurano** [comment]
Great. Specifying both color and itemRGB might set the description line and the track items separately, which is what we want. Go ahead and make a PR.
