### ISSUE TITLE
Normalize read counts by 1M reads

### ISSUE THREAD

**Issue by mattmaurano** [mauranolab/mapping#217]
John,

Here's an outline -- can you take a look? The idea is that we now report reads / 1M analyzed reads rather than absolute counts.

merge_bamintersect.sh - will need to run samtools -c -F 512 on bam1 
counts_table.sh - pass new argument with the number of analyzed reads, normalize read counts per 1M reads
submit_bamintersect.sh - update list of special cases for bam1

**Comment by cadley-nyulangone** [comment]
I think the first two will be straight forward.

For the third, would just passing in <pre>--bam1_exclude_flags 3078</pre> when you call submit_bamintersect.sh do what you want?   That would get rid of all the bam1 proper pairs when sort_bamintersect is running, before the code even gets to merge_bamintersect.

**Comment by cadley-nyulangone** [comment]
I have a version of bamintersect working where the number of reads reported in the counts.txt files is calculated as follows:
<pre>
reads reported = int(1,000,000 * (number of reads in the range) / (total reads from the sample) + 0.5)
                                  ============================
                                 This is what we currently report
</pre>
total reads is gotten like this:
<pre>
num_bam1_reads=$(samtools view -c -F 512 ${bam1}) 
</pre>
So when bam1=capture/Bl6_Cast_Sox2_Sox2_143kb_C1-BS07694A/Bl6_Cast_Sox2_Sox2_143kb_C1-BS07694A.mm10.bam
num_bam1_reads=36759702

The mm10_vs_LP140.informative.counts.txt file for this sample originally had only 3 reads reported.  That comes out as zero reads per million with the new calculation.  Would it be better to report with floating rate precision, or some bigger normalization number?

**Comment by mattmaurano** [comment]
Let's do per 10M reads, that should keep most values above 1

Do you need the +0.5?

**Comment by cadley-nyulangone** [comment]
The .5 adds the rounding functionality.  I can just truncate if we don't need it.

**Comment by mattmaurano** [comment]
Rounding is fine
