### ISSUE TITLE
Missing HTML summary table

### ISSUE THREAD

**Issue by mattmaurano** [mauranolab/mapping#244]
John,

Can you look into why there is no HTML summary table for the mm10 FCHG3CTBGXC ChIP-seq track group?

$ cat /vol/cegs/mapped/FCHG3CTBGXC/chipseq/readcounts.summary.txt 
Sample_Name     BS      Genome  Num_sequenced_reads     Num_pass_filter_alignments      Prop_pass_filter_alignments     Num_mitochondria_reads    Prop_mitochondria_reads Num_analyzed_reads      Prop_analyzed_reads     Num_duplicate_reads     Prop_duplicate_reads      SPOT
Bl6_Cast_dPiga_dSox2_pLP167_D11_StringentIP     CTCF    BS03752A        52383632        180     0       0       0       152     078       0.513   0.9718

**Comment by cadley-nyulangone** [comment]
The readcounts.summary.txt file is bad. It looks like this:


*Sample_Name                                  BS    Genome
 Num_sequenced_reads  Num_pass_filter_alignments
 Prop_pass_filter_alignments  Num_mitochondria_reads
 Prop_mitochondria_reads  Num_analyzed_reads  Prop_analyzed_reads
 Num_duplicate_reads  Prop_duplicate_reads
 SPOTBl6_Cast_dPiga_dSox2_pLP167_D11_StringentIP  CTCF  **BS03752A**
 52383632             180                         0
   0                       0                        152                 0
                 78                   0.513                 0.9718*

I'm trying to figure out why that is happening.  The other ChiP's seem OK,
so it is a little mystifying.

Jhn

**Comment by mattmaurano** [comment]
John, how is this coming on? Does regenerating readcounts.summary.txt fix the problem?

**Comment by cadley-nyulangone** [comment]
If the readcounts file is fixed, the table should get made as expected.
However, I haven't been able to figure out why this particular readcounts
file gets formatted the way it does, when the rest don't.

**Comment by mattmaurano** [comment]
Does regenerating readcounts.summary.txt fix the problem with that file?:

**Comment by cadley-nyulangone** [comment]
No, it doesn't.

Looking into it.

**Comment by cadley-nyulangone** [comment]
This is the sample name of the problem sample:

*Bl6_Cast_dPiga_dSox2_pLP167_D11_StringentIP-CTCF-BS03752A*


It is processed by this section of mapped_readcounts.sh

find ${dir} -regextype posix-awk -maxdepth 2 -regex
".+\/[^\/]+\-[^\/]+\/.+" -and -name "analysis.*.o*" | xargs grep -h -A 11
"Num_sequenced_reads" | awk 'BEGIN {skip=0} $0=="--" {skip=0;next} $0==""
{skip=1;next} skip==0' | grep -v -e "syntax[ _]error" | grep -v "Num_SE_" |
grep -v "Prop_SE_" |
perl -p -e's/[ \t]\(?([\d\.]+)\%\)?/\t$1/g;' -e's/ /_/g;' -e's/\-/\t/g;' |
awk -F "\t" 'BEGIN {OFS="\t"; print "Label", "Value", "Sample_Name", "BS",
"Genome"} $2!="" {print $1, $2, $4, $5, $6} $3!="" {gsub("Num_", "Pct_",
$1); if($3=="NA%") {$3="NA"} print $1, $3, $4, $5, $6}' | cut -f1-6 >
$TMPDIR/readcounts.summary.long.txt



This part of the perl code *-e's/\-/\t/g;' * separates the CTCF and
BS03752A into separate tab delimited fields:

*Num_sequenced_reads^I52383632^I^IBl6_Cast_dPiga_dSox2_pLP167_D11_StringentIP^ICTCF^IBS03752A^Icegsvectors_LP167*


That creates an unexpected field order for the awk code above, and is what
causes the problem.  awk puts CTCF where the BS number should be, and the
BS number replaces the genome.

The "*-CTCF*" should remain attached to the sample name, as it does for the
other chipseq samples.

What I don't understand yet is why this does not happen to all the samples
that have something like this in their names:  "-CTCF-BS03752A". They
should all have this problem, but don't.

For example see this in
*/vol/cegs/mapped/FCHV53GBGXB/chipseq/readcounts.summary.txt*

*Bl6_Cast_dPiga_dSox2_pLP140_A1-CTCF BS03463A    cegsvectors_LP140*


John

**Comment by cadley-nyulangone** [comment]
Have we had a chipseq since last Feb ?

This might have broken the code:
[image: image.png]

John

**Comment by cadley-nyulangone** [comment]
It looks like our problem sample's readcounts file got re-ran in May, after
the above change was made.
