### ISSUE TITLE
Merge in latest daler/trackhub

### ISSUE THREAD

**Issue by mattmaurano** [mauranolab/mapping#264]

**Comment by andremrsantos** [comment]
Using github, I compared our trackhub fork to the original repository (at fork time) and found 3 edited files. Here is a comparison of our edits to the current delear/trackhub by file:

- `trackhub/version.py`
    - just a change of version label, it should have no effect
- `trackhub/track.py`
    - The `SuperTrack` parameter `supertrackonoff=""` has no correspond to the current version, but I'm
      not sure the effect of this change beside adding hide/show. We would have to remove the following from `MakeTrackhub.py`:
https://github.com/mauranolab/mapping/blob/fdb323d23ad461545bf71420e1c09b0aace552ef/dnase/trackhub/MakeTrackhub.py#L163
    - `s.append('    ' + line)` was replaced by `s.append(constants.INDENT + line)` which fixes the original issue
-  `trackhub/constants.py`
    - They moved all track parameters specifications to `trackhub/parsed_params.py` and changed the parameter specification pattern from `Parameter` to `Param` that you specify once and which tracks it is included.
    - They didn't added any parameter equivalent to `applyMinQual` or `minQual`
    - They included a `dimensionAchecked` and changed a little `dimensions <dimX=gTag#> [dimY=gTag#] [dimA=gTag# ...]` for `subGroups` tracks only.
- They move version from `0.2.3` to `0.2.4` which should not include any breaking change

- see comparison at: https://github.com/daler/trackhub/compare/master...mauranolab:master#

**Comment by mattmaurano** [comment]
What would it take to merge in their changes? Can you categorize the functional commits made to our fork as?
1) no longer needed, master made equiv change
2) still needed and can merge cleanly
3) still needed but conflicting changes

**Comment by andremrsantos** [comment]
As is right now, if we merge their changes we would have to basically rewrite our changes given the major change to `trackhub/constants.py`.

Our changes by category:

1. no longer needed, master made equivalent change
    - added `s.append(' ' + line)` on `trackhub/track.py`
    -  added `dimensionAchecked` parameter
2. still needed and can merge cleanly
3. Still needed but conflicting changes
    - added `applyMinQual` and `minQual` parameters to `vcfTabix`
4. not functional change (we either don't use or doesn't affect function)
    - added `dimensionXchecked` and `dimensionYchecked` parameters
    - added `supertrackonoff=""` parameter to `SuperTrack`
    -  updated version

**Comment by mattmaurano** [comment]
How come you say dimensionXchecked/dimensionYchecked and supertrackonoff="" are not a functional changes? I don't think the former are used in MakeTracks.py at the moment but if I'm reading your assessment correctly daler still needs a patch to support. Similarly, unless they corrected the supertrack issue then that patch is still needed as well.

**Comment by andremrsantos** [comment]
- If you want to include support to `dimensionXchecked/dimensionYchecked` we will also need to implemente, however it isn't used in `MakeTrackhub.py` right now. I've edited previous comment and move to (3)
- `supertrackonoff=""` it is used, but it doesn't look to produce major function change. I've edited and moved to (2)
- Which supertrack issue? The tab or `supertrackonoff=""`?
- Yes and not... the conflicts in (3) would have to be rewritten to their `parsed_params.py` to use their new interface, but the code change is relative easy to implement based on the current code. Does it makes sense?

**Comment by mattmaurano** [comment]
Take a look at the commit history in our fork -- the supertrackonoff="" is almost certainly functional.

Assuming you can re-implement the conflicting changes, what's the best way to merge changes like this into our repository? I'm mainly interested in reviewing the diff versus the latest daler repository so I can compare it to our patchset vs. the older version.

**Comment by andremrsantos** [comment]
I've made a pull request to updated our code to dealer version (as a trial for now). However, I need write permission to fix the conflicts. Can you allow me?

**Comment by andremrsantos** [comment]
I've made a new trial PR request, where I merged our version with dealers locally (instead on github). I've commented on the merge conflict edits which conflicts were fixed and what I choose in each case. Next, I've re-implemented our parameters under two commits.
