### ISSUE TITLE
Color bigBed tracks by strand

### ISSUE THREAD

**Issue by mattmaurano** [mauranolab/mapping#266]
uses colorByStrand r,g,b r,g,b (set to blue forward / red reverse like BAM, etc.)

This should apply to any bigBed tracks with 6-8 columns (i.e. having a strand but not itemRgb)

Required new daler/trackhub -- see #264

**Comment by andremrsantos** [comment]
On `MakeTrackhub.py` this appear to affect only Genotypes (only bigBed 6+ https://github.com/mauranolab/mapping/blob/c792f38cec915af9077f7ff8dcbbd303ce97eab3/dnase/trackhub/MakeTrackhub.py#L577), is that right?

**Comment by mattmaurano** [comment]
Andre, I think you're right. No, Genotypes have manually set colors already. So I think this mainly applies to assembly tracks which don't go through MakeTracks.py or trackhub. I'll take this.
